import image from './components/image';
import custom from './components/custom';
import form from './components/form';
import div from './components/div';
import label from './components/label';
import link from './components/link';
import list from './components/list';
import section from './components/section';
import main from './components/main';
import page from './components/page';
import numberInput from './components/numberInput';
import externalLink from './components/externalLink';
import textInput from './components/textInput';
import map from './components/map';
import prop from './hooks/prop';
import routes from './hooks/routes';
import route from './hooks/route';
import text from './hooks/text';
import number from './hooks/number';
import customHook from './hooks/custom';
import siteContext from './hooks/siteContext';
import styles from './hooks/styles';
import Component from './types/component';
import Hook from './types/hook';
import apolloClient from './hooks/apolloClient';
import query from './hooks/query';
import mutation from './hooks/mutation';
import span from './components/span';
import textFromVariable from './hooks/textFromVariable';

export const components: Component[] = [main, div, link, externalLink, form, image, section, list, label, custom, page, numberInput, textInput, map, span];
export const hooks: Hook[] = [prop, routes, route, text, number, customHook, siteContext, styles, apolloClient, query, mutation, textFromVariable];
