import image from './components/image';
import custom from './components/custom';
import form from './components/form';
import flexbox from './components/flexbox';
import label from './components/label';
import link from './components/link';
import list from './components/list';
import section from './components/section';
import main from './components/main';
import page from './components/page';
import numberInput from './components/numberInput';
import prop from './hooks/prop';
import routes from './hooks/routes';
import text from './hooks/text';
import number from './hooks/number';
import customHook from './hooks/custom';
import siteContext from './hooks/siteContext';
import styles from './hooks/styles';
import Component from './types/component';
import Hook from './types/hook';

export const components: Component[] = [main, flexbox, link, form, image, section, list, label, custom, page, numberInput];
export const hooks: Hook[] = [prop, routes, text, number, customHook, siteContext, styles];
